resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
patchesStrategicMerge:
- manager_webhook_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/jpinsonn/network-observability-operator
  newTag: 1466-nodedir-4
commonLabels:
  app: netobserv-operator
