apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
  namespace: operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: loki-operator
  source: #TODO: not yet available
  sourceNamespace: olm