apiVersion: flows.netobserv.io/v1alpha1
kind: FlowMetric
metadata:
  labels:
    app.kubernetes.io/name: flowmetric
    app.kubernetes.io/instance: flowmetric-sample
    app.kubernetes.io/part-of: netobserv-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: netobserv-operator
  name: flowmetric-sample
spec:
  # Example, counting flows per port <= 9999
  # More examples in config/samples/flowmetrics
  metricName: service_ports_total
  type: Counter
  labels: [DstPort]
  filters:
  - field: DstPort
    value: "^\\d\\d?\\d?\\d?$"
    matchType: Regex
  - field: Duplicate
    value: "true"
    matchType: NotEqual
  - field: FlowDirection
    value: "1|2"
    matchType: Regex
