apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: release-netobserv-1-11-2-0
  namespace: ocp-network-observab-tenant
  labels:
    release.appstudio.openshift.io/author: 'jtakvori'
spec:
  releasePlan: netobserv-zstream
  snapshot: netobserv-zstream-20260511-162933-000
  data:
    releaseNotes:
      type: RHSA
      cves:
        - key: CVE-2026-42041
          component: network-observability-console-plugin-zstream
        - key: CVE-2026-42041
          component: network-observability-console-plugin-pf4-zstream
        - key: CVE-2026-42039
          component: network-observability-console-plugin-zstream
        - key: CVE-2025-69873
          component: network-observability-console-plugin-pf4-zstream
        - key: CVE-2026-42043
          component: network-observability-console-plugin-zstream
        - key: CVE-2026-42043
          component: network-observability-console-plugin-pf4-zstream
        - key: CVE-2026-42033
          component: network-observability-console-plugin-zstream
        - key: CVE-2026-42033
          component: network-observability-console-plugin-pf4-zstream
        - key: CVE-2026-42035
          component: network-observability-console-plugin-zstream
        - key: CVE-2026-42035
          component: network-observability-console-plugin-pf4-zstream
        - key: CVE-2026-40895
          component: network-observability-console-plugin-zstream
        - key: CVE-2026-40895
          component: network-observability-console-plugin-pf4-zstream
        - key: CVE-2026-40175
          component: network-observability-console-plugin-zstream
        - key: CVE-2026-40175
          component: network-observability-console-plugin-pf4-zstream
        - key: CVE-2025-62718
          component: network-observability-console-plugin-zstream
        - key: CVE-2025-62718
          component: network-observability-console-plugin-pf4-zstream
        - key: CVE-2026-4800
          component: network-observability-console-plugin-zstream
        - key: CVE-2026-4800
          component: network-observability-console-plugin-pf4-zstream
        - key: CVE-2026-32282
          component: flowlogs-pipeline-zstream
        - key: CVE-2026-32280
          component: network-observability-cli-zstream
        - key: CVE-2026-25679
          component: network-observability-cli-zstream
