apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: lokistack
  namespace: netobserv
spec:
  tenants:
    mode: openshift-network
  managementState: Managed
  limits:
    global:
      retention:
        days: 1
  replicationFactor: 1
  storage:
    schemas:
      - effectiveDate: '2020-10-11'
        version: v11
    secret:
      name: test
      type: s3
  size: 1x.extra-small
  storageClassName: gp2
