name: Build and push to quay.io
on:
  push:
    branches: [ main ]

env:
  REGISTRY_USER: netobserv+github_ci
  REGISTRY: quay.io/netobserv
  IMAGE: network-observability-operator
  ORG: netobserv
  VERSION: main

jobs:
  push-image:
    name: push image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19']
    steps:
      - name: install make
        run: sudo apt-get install make
      - name: set up go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: checkout
        uses: actions/checkout@v3
      - name: docker login to quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ secrets.QUAY_SECRET }}
          registry: quay.io
      - name: get short sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: build images
        run: IMAGE_ORG=${{ env.ORG }} IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.VERSION }} make image-build
      - name: push images
        run: IMAGE_ORG=${{ env.ORG }} IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ env.VERSION }} make image-push
      - name: build and push manifest
        run: IMAGE_ORG=${{ env.ORG }} VERSION=${{ env.VERSION }} make ci-manifest
      - name: print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
      - name: build bundle
        run: IMAGE_ORG=${{ env.ORG }} VERSION=${{ env.VERSION }} PLG_VERSION=${{ env.VERSION }} FLP_VERSION=${{ env.VERSION }} BPF_VERSION=${{ env.VERSION }} BUNDLE_VERSION=0.0.0-${{ env.VERSION }} make bundle bundle-build
      - name: push bundle to quay.io
        id: push-bundle
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE }}-bundle
          tags: v0.0.0-${{ env.VERSION }}
          registry: ${{ env.REGISTRY }}
      - name: build catalog
        run: IMAGE_ORG=${{ env.ORG }} BUNDLE_VERSION=0.0.0-${{ env.VERSION }} make catalog-build
      - name: push catalog to quay.io
        id: push-catalog
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE }}-catalog
          tags: v0.0.0-${{ env.VERSION }}
          registry: ${{ env.REGISTRY }}
      - name: print images reference
        run: |
          echo "Images: ${{ steps.push-to-quay.outputs.registry-paths }}, ${{ steps.push-bundle.outputs.registry-paths }}, ${{ steps.push-catalog.outputs.registry-paths }}"

  codecov:
    name: Codecov upload
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19']
    steps:
    - name: install make
      run: sudo apt-get install make
    - name: set up go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: checkout
      uses: actions/checkout@v3
    - name: Test
      run: make test
    - name: Report coverage
      uses: codecov/codecov-action@v2.1.0
      with:
        files: ./cover.out
        flags: unittests
        fail_ci_if_error: false
